### ISSUE TITLE
Integrate Tubular Common

### ISSUE THREAD

**Issue by geoperez** [unosquare/tubular-nodejs#3]
Integrate Tubular Common

**Comment by geoperez** [comment]
Status?

**Comment by AnyxLeo** [comment]
It got on fire

Enviado desde Correo para Windows 10

De: Geovanni Perez
Enviado: Monday, June 10, 2019 1:44 PM
Para: unosquare/tubular-nodejs
CC: Ana Atayde; Assign
Asunto: Re: [unosquare/tubular-nodejs] Integrate Tubular Common (#3)

Status?

**Comment by geoperez** [comment]
Done!
